[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   netbios name = libraryit-server
   security = user
   map to guest = Bad User
   
   log file = /var/log/samba/libraryit.log
   log level = 3
   
   # VFS Audit Fix
   vfs objects = full_audit
   full_audit:prefix = %u|%I|%m|%S
   full_audit:success = mkdirat rename unlink open
   full_audit:failure = connect
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   read only = yes
   valid users = @staff, @readonly

[papers]
   path = /libraryit/papers
   browseable = yes
   read only = yes
   valid users = @staff, @readonly

[sourcecode]
   path = /libraryit/sourcecode
   browseable = no 
   read only = no
   valid users = @staff

[docs]
   path = /libraryit/docs
   browseable = yes
   read only = yes
   write list = librarian
   valid users = @staff